AOT-Technologies/forms-flow-ai-micro-front-ends

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/resourceBundles/bg/resourceBundles.js, forms-flow-admin/src/resourceBundles/de/resourceBundles.js, forms-flow-admin/src/resourceBundles/en/resourceBundles.js, forms-flow-admin/src/resourceBundles/fr/resourceBundles.js, forms-flow-admin/src/resourceBundles/pt/resourceBundles.js, forms-flow-admin/src/resourceBundles/zh/resourceBundles.js
* ADDED INTERNATIONALIZATION UPDATES ON ADMIN
* https://aottech.atlassian.net/browse/FWF-2138
=> Translation updates on admin

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/dashboard/index.tsx
https://aottech.atlassian.net/browse/FWF-2306
initial authorization check fix
=> Dashboard nodata fix

forms-flow-nav/src/constants/userContants.js, forms-flow-nav/src/helper/user.js
Updated ENV ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK #To Enable Role level permission check for enabling Application and Removed user_Access_permission env
=> Updated show application Env

forms-flow-nav/src/Navbar.jsx, forms-flow-nav/src/root.component.js
1. fixing unauthorize issue when login
=> push base url before logout function invoke

forms-flow-nav/src/Navbar.jsx
=> fixed multi tenancy issue

forms-flow-admin/src/components/roles/roles.scss, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-nav/src/Navbar.css
JIRA : https://aottech.atlassian.net/browse/FWF-2140
CHANGES : gave full length to head rule and also removed the gap between the headings
=> UI fix for headings in nav

forms-flow-admin/Dockerfile, forms-flow-nav/Dockerfile, forms-flow-service/Dockerfile, forms-flow-theme/Dockerfile
=> Updated expose on docker file

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-2140
Changes:  button and user filter style changed
=> UI Changes in roles and users part

forms-flow-admin/package.json, forms-flow-admin/src/components/footer/footer.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-2382
=> Admin module version changed to 5.2.1-alpha

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Added internationalization for delete modal
=> Internationalization for delete modal

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> updated roles creation function

forms-flow-service/package.json, forms-flow-service/src/constants/constants.ts, forms-flow-service/src/formsflow-services.ts, forms-flow-service/src/helpers/helperServices.ts
created a helper service to migrate all common functions from web to service module also migrated date and time function to helper services
=> helper services

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Jira: https://aottech.atlassian.net/browse/FWF-2469
Internationalization is added for the access denied message for unauthorized file upload. 
added sentence:  "Access restricted by its designer..!"
=> RBAC Check for unauthorized designers- Internationalization

forms-flow-service/package-lock.json
=> package_lock_update

forms-flow-admin/src/components/roles/roles.tsx
=> updated regex

forms-flow-admin/src/components/roles/roles.tsx
=> support for forward slash

forms-flow-theme/src/global.css
=> Ui-enhancement changes.

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> Internationalization for 'Application ID' in application page

forms-flow-nav/src/Navbar.css, forms-flow-nav/src/Navbar.jsx
Jira: check 1: https://aottech.atlassian.net/browse/FWF-2508
EPD changes.
=> Moved the User Name to the right end of the Nav bar

forms-flow-service/src/helpers/helperServices.ts
date  is now compactable for all browsers
=> date issues fixed for all browsers

forms-flow-admin/src/components/users/users.tsx
https://aottech.atlassian.net/browse/FWF-2529
Previous
Now
=> Style issue fix for admin tab

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> fixed dmn internationalization

forms-flow-admin/src/components/users/users.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> Updated internationalization

forms-flow-service/src/constants/constant.ts, forms-flow-service/src/helpers/helperServices.ts
utc time zone changed to system time zone
=> Time zone fix

forms-flow-nav/src/Navbar.css, forms-flow-nav/src/Navbar.jsx
=> new navbar design

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/dashboard/insightDashboard.scss, forms-flow-admin/src/components/footer/footer.tsx, forms-flow-admin/src/components/users/users.tsx
=> Admin fontawsome fix

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/dashboard/insightDashboard.scss, forms-flow-admin/src/components/roles/roles.scss, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.scss, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/containers/head.tsx, forms-flow-admin/src/index.scss, forms-flow-admin/src/index.tsx, forms-flow-nav/src/Navbar.jsx, forms-flow-service/src/helpers/helperServices.ts, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts, forms-flow-theme/src/bootstrapOverride.scss, forms-flow-theme/src/global.scss
https://aottech.atlassian.net/browse/FWF-2743
=> Admin UI refresh

forms-flow-theme/src/components/custom-table.scss, forms-flow-theme/src/global.scss
Changes : Font size and Table margin changes
Screenshots :
=> font size and table margin update

forms-flow-admin/src/components/roles/roles.tsx
* JIRA: https://aottech.atlassian.net/browse/FWF-2755
* Cancel button changes in admin tab
=> Cancel button changes 

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Changes: 
Internationalisation updates for new UI changes
Screenshots :
=> Internationalisation updates

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> translation issue fixed

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx
* Fixed margin issues in admin tab
=> Margin fixes 

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-theme/src/components/button.scss, forms-flow-theme/src/global.scss, forms-flow-theme/src/overrideClasses/bootstrapOverride.scss, forms-flow-theme/src/overrideClasses/formioComponentOverride.scss
=> button padding changed

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> pending changes in translation

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> Bundle translation update

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: https://aottech.atlassian.net/browse/FWF-2795
=> Bundling translation updates

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: https://aottech.atlassian.net/browse/FWF-2798
=> Updated task page translation

forms-flow-service/src/keycloak/KeycloakService.ts
Added the logout method in keycloak services.
=> Auto-logout issue

forms-flow-admin/src/components/roles/roles.tsx
=> Fixed Clear button 

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
CHANGES : 
search by bundle name internationalisation changed
SCREENSHOT :
=> search by bundle name internationalisation changed

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
* Updated new text translation of tasks page
=> Tasks page translation

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
changes : filter and submission internationalisation updated
screenshot :
=> filter and submission internationalisation updated

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
CHANGES : Internationalisation change in draft search
SCREENSHOT :
=> Internationalisation change in draft search

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> Pagination translation update

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> Submission and task page translation

forms-flow-admin/src/components/roles/roles.tsx
https://aottech.atlassian.net/browse/FWF-2818
=> disabled default users for multitenant

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts, forms-flow-theme/src/overrideClasses/bootstrapOverride.scss
Jira : https://aottech.atlassian.net/browse/FWF-2856
1. International changes 
2. Accessibility fixes in form bundling
=> accessbility fix in ee

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/footer/footer.tsx, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/index.tsx, forms-flow-nav/src/Navbar.jsx, forms-flow-theme/src/components/custom-table.scss
issue : https://aottech.atlassian.net/browse/FWF-2805
changes : bootstrap upgrade changes
screenshots:
=> bootstrap upgrade changes

forms-flow-theme/src/components/custom-table.scss, forms-flow-theme/src/global.scss, forms-flow-theme/src/overrideClasses/formioComponentOverride.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-2879
changes in form menu ,create form and edit form pages with new bootstrap
=> changes for form page with new bootstrap

forms-flow-theme/src/overrideClasses/bootstrapOverride.scss
1, Added color for table header in create bundle page
=> bundle table-header color added

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/dashboard/insightDashboard.scss, forms-flow-admin/src/components/roles/roles.scss, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.scss, forms-flow-admin/src/components/users/users.tsx
JIRA:https://aottech.atlassian.net/browse/FWF-2882
CHANGES: Bootstrap fixes in admin page
SCREENSHOTS :
=> Bootstrap fixes in admin page

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-theme/src/global.scss
1.Penidng changes in role page
=> pending changes

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-nav/src/Navbar.jsx
JIRA:
https://aottech.atlassian.net/browse/FWF-2909
data-test id added in navbar and admin
=> data-testid added in navbar and admin

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx
JIRA:
https://aottech.atlassian.net/browse/FWF-2909
data-test id added in pending admin part
=> data-test id added in pending admin part

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/containers/head.tsx
JIRA:
https://aottech.atlassian.net/browse/FWF-2958
missed data test id added in admin part
=> missed data test id added in admin part

forms-flow-theme/src/global.scss
Added Color variables to the micro front end root.
=> Color Variables Added to Micro front-end.

forms-flow-theme/src/overrideClasses/formioComponentOverride.scss
JIRA:
https://aottech.atlassian.net/browse/FWF-2956
Changes
wizard style issue fixed
Screenshots :
=> wizard style issue fixed

forms-flow-admin/src/components/roles/roles.tsx
https://aottech.atlassian.net/browse/FWF-2918
=> removed default submit call of form

forms-flow-theme/src/global.scss
Added Color variables for equalizing requirements for modeler file
=> Added Essential color variables for modeler file.

forms-flow-nav/src/Navbar.jsx
1. added event key to close the nav bar on select
=> Fixed navbar collapses toggle on nav option select

forms-flow-nav/src/Navbar.jsx
JIRA:https://aottech.atlassian.net/browse/FWF-3056
Issue:
Fix:
Also fixed for view submitted form
=> Forms and submission highlight issue fixed

forms-flow-nav/src/Navbar.css, forms-flow-nav/src/Navbar.jsx
JIRA:https://aottech.atlassian.net/browse/FWF-2961
DESCRIPTION:Longer app name issue fixed
SCREENSHOTS:
=> Longer app name issue fixed

forms-flow-nav/src/Navbar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-2558
SCREENSHOT:
=> favicon issue fixed 

forms-flow-admin/src/components/users/users.tsx
Handled Search and Filter in front-end for Admin User table.
=> Admin Search and filter updates in Frontend.

forms-flow-nav/src/Navbar.css, forms-flow-nav/src/Navbar.jsx
Jira : https://aottech.atlassian.net/browse/FWF-2961
Changes : style change and tooltip added to app name
Screenshots:
=> style change and tooltip added to app name

forms-flow-admin/src/endpoints/config.ts, forms-flow-nav/src/constants/constants.js
Changes to add custom Keycloak relative path
=> Changes to add custom Keycloak relative path

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Jira : 
Changes : Internationalization added for product fruit period notification and filter delete modal
Screenshots :
=> Internationalization added for product fruit period notification and filter delete modal

forms-flow-admin/package-lock.json, forms-flow-admin/package.json, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/endpoints/index.ts, forms-flow-admin/src/services/users/index.ts, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
https://aottech.atlassian.net/browse/FWF-2922
=> Add Users to keyclaok from admin tab

forms-flow-admin/src/components/users/users.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
https://aottech.atlassian.net/browse/FWF-3169
=> added translation files

forms-flow-integration/src/components/PremiumSubscription/index.tsx, forms-flow-integration/src/constants/index.ts, forms-flow-integration/src/index.tsx, forms-flow-nav/src/Navbar.jsx, forms-flow-nav/src/constants/constants.js
jira : https://aottech.atlassian.net/browse/FWF-3107
description: page for premium subscription is added in integration
screenshots :
=> page for premium subscription is added in integration

forms-flow-admin/src/components/users/users.scss, forms-flow-admin/src/components/users/users.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> Updated add user modal for multitenancy admin

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
* Added internationalization for integration
=> translations update for integration

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Changes : Internationalisation for integration
Screenshots :
=> internationalisation for integration

forms-flow-admin/src/components/users/users.tsx
=> Validation error retaining issue fixed

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> translation fix added

forms-flow-nav/src/Navbar.jsx
=> added id for navbar

forms-flow-integration/src/components/PremiumSubscription/index.tsx, forms-flow-integration/src/index.scss, forms-flow-nav/src/Navbar.jsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> updates based on marketing

forms-flow-integration/src/components/PremiumSubscription/index.tsx
jira : https://aottech.atlassian.net/browse/FWF-3107
description: footer added for integration
screenshots :
=> footer added for integration

forms-flow-integration/src/components/PremiumSubscription/index.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> added translation changes and updated href

forms-flow-admin/src/components/users/users.scss, forms-flow-admin/src/index.scss, forms-flow-admin/src/variables.scss, forms-flow-nav/src/Navbar.jsx, forms-flow-nav/src/Navbar.scss, forms-flow-nav/src/variables.scss, forms-flow-theme/src/scss/_button.scss, forms-flow-theme/src/scss/_layout.scss, forms-flow-theme/src/scss/_table.scss, forms-flow-theme/src/scss/_theme.scss, forms-flow-theme/src/scss/_typography.scss, forms-flow-theme/src/scss/_variables.scss, forms-flow-theme/src/scss/index.scss
Removed all custom color variables and added Bootstrap variables for theme.
=> Bootstrap changes for theme colors.

forms-flow-theme/scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3334
Fix preview:
=> FWF-3334: [Bugfix] Resolved button color issue in dev

forms-flow-theme/scss/_layout.scss, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss
=> FWF-3335: [Bugfix] Resolved color issues

forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/external/toastify.scss
The progress bar was not visible in the toast messages. 
#screenshots
=> FWF-3336:[bugfix] Toastify UI fix.

forms-flow-theme/scss/external/toastify.scss
jira: https://aottech.atlassian.net/browse/FWF-3336
Screenshot:
=> FWF-3336:[bugfix] Toastify UI fix - 2

forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3334
=> FWF-3334: [Bugfix] fixed color changes

forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_theme.scss
Jira: https://aottech.atlassian.net/browse/FWF-3350
#Screenshot:
=> FWF-3350: [Bugfix] Client form form table - accordion fix.

forms-flow-nav/src/Navbar.jsx, forms-flow-nav/src/Navbar.scss, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss
Jira:https://aottech.atlassian.net/browse/FWF-3349
changes:navbar style updates
screenshots:
=> FWF-3349:[Bugfix] navbar style changes

forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss
Added visible focus indicator for accessibility. 
Jira:
Screenshot:
=> FWF-3281: [Bugfix] Visible-focus-indicator added in form page

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/containers/head.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3288
https://aottech.atlassian.net/browse/FWF-3290
=> :accessibility:  Bugfix/FWF-3290 lacks list item

forms-flow-theme/scss/_variables.scss
Jira https://aottech.atlassian.net/browse/FWF-3358
Screenshot:
=> FWF3358: [Bugfix] Color difference in form create page

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
1. Added translation for default filter feature
=> FWF:3305 [Feature] Added internationalization for default filter

forms-flow-nav/src/Navbar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-3374
Issue:
Fix:
=> FWF-3374: [Bugfix] Removed login from navbar

CHANGELOG.md
=> [Sync 🔗] Sync/master to develop 6.0.2

forms-flow-nav/src/Navbar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-3423
1 . alt attribute updated for logo
=> FWF-3423:[Bugfix] Fixed alt attribute

forms-flow-admin/src/containers/head.tsx, forms-flow-admin/src/index.scss, forms-flow-integration/src/containers/head.tsx, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_icon.scss, forms-flow-theme/scss/_layout.scss, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_table.scss, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_typography.scss, forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/index.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3217
1. Created separate SCSS files for components 
2.  Removed  unused classes 
3.  Updated bootstrap classes and variables
=> fwf-3217: [Modified] created files for components

forms-flow-theme/scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3422
Screenshot: 
Added the outline property to the buttons.
=> FWF-3422:[Bugfix] : added button outline for accessibility.

forms-flow-theme/scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3422
=> Bugfix/fwf-3422 <a> tag visible focus indicator

forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_table.scss, forms-flow-theme/scss/_typography.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3217
1. Removed class related form control focus
2. Fixed table alignment 
3. Updated fontsize
=> 🐛 Bugfix/fwf:3217 accessibility form control update

forms-flow-theme/scss/_button.scss
=> FWF-3422:[Bugfix]-focus indicator for input and check box.

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/endpoints/index.ts, forms-flow-admin/src/services/roles/index.ts, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: https://aottech.atlassian.net/browse/FWF-3324
1.API call added for fetching permissions
2.Added permmision mapping to roles
3.Translation is added
4.Added util to list roles without tenantKey
5.added changes in  search  after removing the tenantkey
=> FWF-3324: [Feature] Added permmision mapping to roles

forms-flow-nav/src/Navbar.jsx, forms-flow-nav/src/constants/constants.js
JIRA: https://aottech.atlassian.net/browse/FWF-3384
1.Added option to display selected language
=> FWF-3384:[Feature] added option to display selected lang

.github/workflows/forms-flow-admin-cd.yml, .github/workflows/forms-flow-integration-cd.yml, .github/workflows/forms-flow-nav.cd.yml, .github/workflows/forms-flow-service.yml, .github/workflows/forms-flow-theme.yml, VERSION
=> Updating version tag to create new version for rbac changes

forms-flow-theme/scss/_theme.scss
Added Base colors for the new design system.
=> FWF-3341:[feature]-color system

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
added translation for multitenant landing page
=> translation fix for multi-tenant login

forms-flow-nav/src/Navbar.jsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-3498
=> navbar initial render fix

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/index.tsx, forms-flow-admin/src/utils/utils.js
JIRA: https://aottech.atlassian.net/browse/FWF-3521
=> Remove tenant key from group listing

.github/workflows/forms-flow-admin-cd.yml, .github/workflows/forms-flow-integration-cd.yml, .github/workflows/forms-flow-nav.cd.yml, .github/workflows/forms-flow-service.yml, .github/workflows/forms-flow-theme.yml, VERSION, forms-flow-admin/package.json, forms-flow-integration/package.json
=> Modified version to 7.0.0-alpha

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/utils/utils.js, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
…
JIRA: https://aottech.atlassian.net/browse/FWF-3540
=>  FWF 3540 [ bugfix] fixed groups showing in multi tenant and label changed

forms-flow-service/package-lock.json, forms-flow-service/package.json
JIRA: 
https://aottech.atlassian.net/browse/FWF-3519
=> updated version

forms-flow-service/package-lock.json, forms-flow-service/package.json
JIRA: 
upgraded the keycloak-js version to 24.0.5
=> updated keycloak version

forms-flow-integration/src/index.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-3567
=> added new roles for integretion

forms-flow-theme/scss/_forms.scss
=> FWF-3534 [Feature] Added style for searchbox

forms-flow-admin/src/index.tsx, forms-flow-nav/src/Navbar.jsx
JIRA: 
1.Fixed admin login showing forms page 
2.Removed unused code  
#screenshots
=> FWF:3560[Bugfix] Fixed Admin Login showing Forms page

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-nav/src/sidenav/Sidebar.scss, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3532
1.svgs added in components
2.new sidebar changes added
3.styles added for custom checkbox and custom tooltip
=> Feature/fwf 3532 overriding styles 

forms-flow-service/package-lock.json, forms-flow-service/package.json
https://aottech.atlassian.net/browse/FWF-3519
JIRA: 
=> updated keycloak to latest version 25.0.4

forms-flow-admin/src/index.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3622
1. Fixed redirecting to "/tenantId"
=> FWF:3622 [BUGFIX] Fixed redirecting to /tenatId

forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3555
1.Added styles for FormInput component
=> FWF:3555-[Feature] Create custom inputbox

forms-flow-components/package.json, forms-flow-components/src/components/CustomComponents/Button.tsx, forms-flow-components/src/components/index.ts, forms-flow-components/webpack.config.js
JIRA: 
button component added in MF
=> button component added in MF

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3534
=> FWF-3534: [Feature] removed and updated styles with icons

forms-flow-components/src/components/CustomComponents/Search.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3534
* Added search component tsx
* search style fixes
=> FWF-3534: Added search component tsx, search style fixes

forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/_forms.scss
JIRA: 
1.Added inputBox in Microfrontend 
2. Added enter button click for icon 
3. Added style for input focus state for both normal and invalid case 
4. Added padding for icon
=> Added inputBox in components

forms-flow-components/src/components/CustomComponents/Pills.tsx, forms-flow-components/src/components/CustomComponents/Radio.tsx, forms-flow-components/src/components/CustomComponents/Tabs.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3595
styles for radio, pill, tabs
=> styles for radio, pill, tabs

forms-flow-components/src/components/CustomComponents/Tabs.tsx, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_modal.scss
JIRA: 
1.className prop added for tabs
2. styles added for modal
=> Feature/modal & tabs styles updated

forms-flow-components/src/components/CustomComponents/ProgressBar.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/_aiAssistant.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3609
screenshot
custom progressbar added and chatbot styles updates
=> custom progressbar added and chatbot styles updates

forms-flow-theme/scss/_aiAssistant.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3609
scroll bar added in chatbot form container
=> scroll bar added in chatbot form container

forms-flow-components/src/components/CustomComponents/Button.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3486
Medium button issue fixed
=> Bugfix/Medium button issue fixed 

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/index.ts
JIRA: https://aottech.atlassian.net/browse/FWF-3619
Reusable Form builder modal added
=> Reusable Form builder modal added

forms-flow-components/src/components/CustomComponents/Search.tsx, forms-flow-theme/scss/_forms.scss
JIRA: 
*  Search padding and height fixed
=> FWF-3534: [Bugfix] Fixed search padding issues

.github/workflows/forms-flow-admin-cd.yml, .github/workflows/forms-flow-nav.cd.yml, .github/workflows/forms-flow-service.yml, .github/workflows/forms-flow-theme.yml, VERSION
=> updated the action files

forms-flow-components/package-lock.json, forms-flow-components/package.json, forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/resourceBundles/i18n.js, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
=> modified formbuilder-modal

forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3739
=> FWF-3739:[Feature] - SaveLayout and Publish

forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/CustomComponents/FormTextArea.tsx, forms-flow-theme/scss/_aiAssistant.scss, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_layout.scss, forms-flow-theme/scss/_mixins.scss, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_table.scss, forms-flow-theme/scss/_typography.scss, forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/customTextArea.scss, forms-flow-theme/scss/fileUpload.scss, forms-flow-theme/scss/inputBox.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3752
- Rework on modal sizing
- Removal of unused styles
- Removal of default variables
- Convertion of styles to variables
- Duplicate code removal
- Standardising css to be compatible to formio
- Nesting of styles
=> FWF-3752 [Bugfix] : Changes as part of css optimisations initial commit

forms-flow-theme/scss/_modal.scss
JIRA: 
width updates for modal
=> FWF-3752 [Bugfix] width updates for modal

forms-flow-theme/scss/_aiAssistant.scss, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_layout.scss, forms-flow-theme/scss/_mixins.scss, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_table.scss, forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/customTextArea.scss, forms-flow-theme/scss/external/formio.scss, forms-flow-theme/scss/fileUpload.scss, forms-flow-theme/scss/inputBox.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3752
Updated css fixes and formatted scss files
=> FWF-3752 [Bugfix] : Updated css fixes and formatted scss files

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA:  https://aottech.atlassian.net/browse/FWF-3667
1. Updated route of subflow
=> feature/FWF3667: Subflow list- route updated

forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/CustomComponents/FormTextArea.tsx, forms-flow-theme/scss/_modal.scss
=> Added name prop into input fields

.github/workflows/forms-flow-component-cd.yml, .github/workflows/pr-notification.yml
=> main to develop

forms-flow-components/src/components/SvgIcons/index.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3821
1. Added disabled color
=> FWF-3821 [featue] added disabled prop in svg icon

forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3739
#Screenshot
=> FWF-3739:[Feature]-css update

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3819
1. removed checking the description is there or not for disable the button
=> Removed description checking while button disable in form Builder modal

forms-flow-components/src/components/CustomComponents/InputDropdown.tsx, forms-flow-theme/scss/_modal.scss
JIRA: 
* Added styles for email action modal-body
=> FWF-3845: [Feature] Added styles for email modal body

forms-flow-components/src/components/CustomComponents/Pills.tsx, forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_modal.scss
=> Added delete svg icon, added common style for multi-select

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3849
=> FWF-3849 [bugfix] data not clearing issue

forms-flow-components/src/components/CustomComponents/ErrorModal.tsx, forms-flow-components/src/components/CustomComponents/ReusableProcessTableRow.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/_modal.scss
=> updated route for decison table and include reusable error modal

forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
=> Disabled revert button if the version is current version

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3849
1. removed setChecked function from prop
2. added title cache
=> added loading and caching title and removed unwanted function from prop

forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
=> Added disabledData prop to disable revert button

forms-flow-components/src/components/CustomComponents/HistoryModal.tsx, forms-flow-theme/scss/external/formio.scss
Issues with UTC date setting and Text issue in history modal. formio color change
JIRA: 
https://aottech.atlassian.net/browse/FWF-3893
https://aottech.atlassian.net/browse/FWF-3897
UTC date showing in history modal fixed
Text change to history modal
Background color issue in formio panel fixed
=> FWF-3892[Bugfix] : issues with UTC date setting and Text issue in history modal. formio color change

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_modal.scss
JIRA: 
*  Added style for expression builder
*  Added tick icon in svg
=> FWF-3846: [Feature] Added style for expression-builder modal

forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3736
style added for not allowing for edit in preview of form
=> added style for preview page

forms-flow-nav/src/sidenav/MenuComponent.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-3426
nav changes regarding multi tenant issue
=> nav changes regarding multi tenant issue

forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
=> changed date format function

forms-flow-components/src/components/CustomComponents/NoDataFound.tsx, forms-flow-components/src/components/CustomComponents/TableFooter.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/_table.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3879
=> FWF-9879:[Feature]Added no records page

forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx
=> added primary button disabled in confirm modal

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/declarations.d.ts, forms-flow-components/src/components/CustomComponents/TableFooter.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3932, https://aottech.atlassian.net/browse/FWF-3945?focusedCommentId=26529
*  Search component added
*  Pagination updations
=> FWF-3922: [Bugfix] Replaced search, fixed pagination updates

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-3967
1. Changed the sidebar text of ‘Sub - flows' to 'Subflows’
2. Fixed sidebar open issue in first page load
=> 🐛 bugfix/fwf-3967:Fixed sidebar open issue in first page load

forms-flow-nav/src/sidenav/ProfileSettingsModal.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-nav/src/sidenav/Sidebar.scss, forms-flow-theme/scss/_modal.scss
JIRA: feature/FWF-3939-language-modal
* Added profile settings modal for language selection
=> Profile settings modal: language selection

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-4049
* Resolved navbar issue
=> Bug fix/fwf 4049 navbar issue fix

forms-flow-components/src/components/CustomComponents/ImportModal.tsx
=> Added drag and drop for import

forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-components/src/components/CustomComponents/ImportModal.tsx, forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4012
=> FWF-4012:[Feature] - Doted line for Migration modal.

forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4042
1. Fixed search ui
=> bugfix/fwf-4042:Fixed search UI

forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
JIRA: 
1. Changed to LOWCODE to No-Code 
2.
=> bugfix/fwf-3914:Fixed no code to bpmn switching ui issue

forms-flow-nav/package.json, forms-flow-nav/src/sidenav/ProfileSettingsModal.jsx, forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4056
=> FWF-4056: [Feature] language modal updated design added

forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3964
1. Fixes style issues in task variables
=> Fixed styles issues in task variable

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4078, https://aottech.atlassian.net/browse/FWF-3981
* Added loader ui in input box - updated in formbuilder
* Removed unwanted formio component panel
=> FWF-4078, FWF-3981: [BugFix] Added loader ui , removed formio component panel

forms-flow-theme/scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3933
Page names are not showing in wizard issue fixed
=> FWF-3933-wizard-page-fix

forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4089
1. Updated custom input with ref 
2. Added autofocus prop for inputdropdown
=> bugfix/fwf-4089:Added autofocus for inputdropdown ==>input

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-4094
* Added new permission check for subflows and decision table
=> FWF-4094: [Feature] Added new permissions for showing sub flows and decision table

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4033
=> FWF-4033: [BugFix] removed wizard check and note from opensource form builder modal

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: 
* Sidebar blank issue fixed
=> sidebar blank issue fixed

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/roles/roles.scss, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.scss, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/index.tsx, forms-flow-components/src/components/CustomComponents/ReusableProcessTableRow.tsx, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4062
https://aottech.atlassian.net/browse/FWF-3867
1.font size issue on dashboard, roles, user tables fixed 
2.style issue fixes for EE and open src
=> Bugfix/fwf 3867 UI issue fix part-1

forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4032
Added Custom class for Scrollbar.
=> FWF-4032:[Feature]- Custom Scrollbar

forms-flow-components/src/components/CustomComponents/ShowPremiumIcon.tsx, forms-flow-nav/src/sidenav/MenuComponent.jsx
JIRA: Requirement 5 in  https://aottech.atlassian.net/browse/FWF-4100
* Added different premium icon color for selected menu
=> [BugFix]: FWF-4100 Added premium icon color change for selected menu

forms-flow-components/src/components/CustomComponents/ImportModal.tsx
=> Disabled primary button on action in importmodal

forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4100
=> UI Issues: form-edit, no-code, variables modal

forms-flow-nav/src/sidenav/ProfileSettingsModal.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx
…
JIRA: https://aottech.atlassian.net/browse/FWF-4100
=> Fixed (nav) [FWF-4056] : fixed navbar lang selection issue and code optimized

forms-flow-nav/src/root.component.js, forms-flow-service/src/constants/constants.ts, forms-flow-service/src/helpers/helperServices.ts, forms-flow-theme/scss/_variables.scss
JIRA:  https://aottech.atlassian.net/browse/FWF-4035
1. Hid sidebar in preview page
=> bugfix/fwf-4035:Hid sidebar in preview page

forms-flow-admin/src/components/dashboard/dashboard.tsx, forms-flow-admin/src/components/dashboard/insightDashboard.scss, forms-flow-admin/src/components/roles/roles.scss, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/users.scss, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/index.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4101
UI modified inside the admin pages
#Screenshots
=> UI modifications in admin pages

forms-flow-nav/src/root.component.js, forms-flow-service/src/helpers/helperServices.ts
JIRA: https://aottech.atlassian.net/browse/FWF-4035
1.Added helper function for showing sidebar
=> bugfix/fwf-4035:added helper fn for showing sidebar

forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4124
1.added maxlength for list of multiselect and made scrollable
=> bugfix/fwf-4124:Added style changes for multi select component

forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4020
Added loader for secondary buton in confirm modal . used for form delete operation
UI fix to have minor padding in form builder top
=> FWF-4020 [Bugfix] loader in delete form added and ui fixes

forms-flow-nav/src/sidenav/MenuComponent.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-nav/src/sidenav/Sidebar.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4130
1. Route fix for bundle listing page
2. Sidebar highlighting issue fixed 
3. Style fixes in sidebar
4. routing issue with bundle submission route fixed
=> FWF-4130 [Bugfix] Navbar fixes for active highlighting , bundle route changes. optimisations

forms-flow-nav/src/sidenav/MenuComponent.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-theme/scss/external/formio.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-4130
https://aottech.atlassian.net/browse/FWF-4043
https://aottech.atlassian.net/browse/FWF-4141
- Sidebar highlighting for formflow and form routes at same time fixed
- Issue with integrations tab collapsing fixed.
- optimisations
- Hidden variable selection in task variable selection modal fixed
=> FWF-4130-4043-4141 [Bugfix] Sidebar issue for form,formsflow and integration tabs fixed

forms-flow-theme/scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4128
=> Updated wizard name issue in variables, updated design

forms-flow-nav/src/root.component.js, forms-flow-nav/src/sidenav/MenuComponent.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-service/src/helpers/helperServices.ts
JIRA: 
https://aottech.atlassian.net/browse/FWF-4136
https://aottech.atlassian.net/browse/FWF-4043
-Sidebar show/hide issues with multi env fixed
-Integrations tab collapsing/opening issues fixed
-Premium icons rendering issue fix
-Multi pages inside integartions supporting active tab fix
=> FWF-4043-4136 [Bugfix] Sidebar issues and integration tab issue fixes

forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
=> added default value for setNewInput in inputdropdown

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/index.scss, forms-flow-theme/scss/_table.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4135
=> Resolved UI issues in roles and table

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-4154
=> Resolved permission matrix issues

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4156
=> updated authorization for dashboards

forms-flow-nav/src/sidenav/Sidebar.jsx
=> updated code for authorization check for dashboard

forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4144
=> FWF-4144:[Feature]- Expression-Area UI fix

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/components/users/index.tsx, forms-flow-admin/src/components/users/users.tsx, forms-flow-admin/src/services/users/index.ts
JIRA: https://aottech.atlassian.net/browse/FWF-4155
1.Fixed page limit issue in users
=> bugfix/fwf-4155:Fixed page limit issue in users

forms-flow-admin/src/components/roles/roles.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4119
=> Updated description validation in role create

forms-flow-admin/src/components/roles/roles.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4119?focusedCommentId=27126
=> Removed asterix for edit role

forms-flow-theme/scss/_modal.scss
JIRA:  https://aottech.atlassian.net/browse/FWF-4192
Issue:
Fix:
=> Rsolved long form name issue in form export

forms-flow-theme/scss/_variables.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4159
=> ui issue fix for submission page

CHANGELOG.md
=> Changelog for MF

VERSION, forms-flow-admin/package-lock.json, forms-flow-admin/package.json, forms-flow-components/package-lock.json, forms-flow-components/package.json, forms-flow-integration/package.json, forms-flow-nav/package.json
=> Modified: [version changed] 7.0.0-alpha to 7.1.0-alpha

README.md
=> Sync/main to develop 7.0.0

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/CustomComponents/FormTextArea.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4013
=> Added maxLength, min Length props to form input and text area

forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4184
1.Fixed selecting variable by clicking on the form component  in task variable modal
=> bugfix/fwf-4184:Fixed selecting variable clicking on the form component issue in task variable modal

forms-flow-admin/src/index.tsx, forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-4223
1. Added publish when the instance is there
2.
=> Fixed: logout button issue

forms-flow-components/src/components/CustomComponents/InputDropdown.tsx, forms-flow-components/src/declarations.d.ts, forms-flow-theme/scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3920
added variables for no code colors
hexadecimal color code changed to css variables using fetcher utility
=> added variables for no code colors(MF)

forms-flow-components/src/components/CustomComponents/ImportModal.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4225
=> updated disable condition

forms-flow-components/src/components/CustomComponents/ImportModal.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4225
=> import button disable fix to release branch

forms-flow-admin/src/index.tsx, forms-flow-nav/src/sidenav/Sidebar.jsx
=> Fixed: logout button issue to release/7.0.0

forms-flow-admin/src/index.tsx, forms-flow-components/src/components/CustomComponents/ImportModal.tsx, forms-flow-nav/src/sidenav/Sidebar.jsx
=> Release/7.0.0 change to main 

forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4118
1. Added style changes for expression builder modal its contents
=> bugfix/fwf-4118:Added style changes for expression builder

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4134
=> quick fix for lang reset

forms-flow-theme/scss/_aiAssistant.scss, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_table.scss, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/customTextArea.scss, forms-flow-theme/scss/external/formio.scss, forms-flow-theme/scss/fileUpload.scss, forms-flow-theme/scss/historyModal.scss, forms-flow-theme/scss/inputBox.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4272
variable updations in border radius and style updates
=> border radius updates in MF

.github/workflows/forms-flow-component-cd.yml, .github/workflows/forms-flow-component-ci.yml, forms-flow-components/jest.config.js, forms-flow-components/jest.setup.js, forms-flow-components/src/__test__/button.test.tsx, forms-flow-components/src/__test__/customInfo.test.tsx, forms-flow-components/src/__test__/pills.test.tsx, forms-flow-components/src/__test__/tableFooter.test.tsx, forms-flow-components/src/__test__/tabs.test.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4318
=> FWF-4318 [feature] Testcase implemented for custom components

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_button.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-4269
=> updated code for support data-test-id and aria labels

forms-flow-components/src/__test__/buildModal.test.tsx
=> Test case [feature] added for build modal

forms-flow-components/src/components/CustomComponents/Button.tsx, forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-components/src/components/CustomComponents/ErrorModal.tsx, forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/CustomComponents/FormTextArea.tsx, forms-flow-components/src/components/CustomComponents/HistoryModal.tsx, forms-flow-components/src/components/CustomComponents/InputDropdown.tsx, forms-flow-components/src/components/CustomComponents/Pills.tsx, forms-flow-components/src/components/CustomComponents/Radio.tsx, forms-flow-components/src/components/CustomComponents/ReusableProcessTableRow.tsx, forms-flow-components/src/components/CustomComponents/SortModal.tsx, forms-flow-components/src/components/CustomComponents/Tabs.tsx, forms-flow-nav/src/sidenav/ProfileSettingsModal.jsx
=> dataTestId text change

forms-flow-components/__mocks__/@formsflow/service.js, forms-flow-components/jest.config.js, forms-flow-components/src/__test__/FormTextArea.test.tsx, forms-flow-components/src/__test__/ShowPremiumIcon.test.tsx, forms-flow-components/src/__test__/confirmModal.test.tsx, forms-flow-components/src/__test__/errorModal.test.tsx, forms-flow-components/src/__test__/formBuilderModal.test.tsx, forms-flow-components/src/__test__/formInput.test.tsx, forms-flow-components/src/__test__/historyModal.test.tsx, forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
1. error modal
2. form input
3. form textarea
4. ShowPremiumIcon
JIRA:  https://aottech.atlassian.net/browse/FWF-4318
=> Testcase implemented for

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-components/src/components/CustomComponents/NoDataFound.tsx, forms-flow-components/src/components/CustomComponents/TableFooter.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_variables.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-4316
https://jam.dev/c/c4653466-21b1-4be9-a393-add764a746a5
=> updated style fix

forms-flow-components/src/__test__/FormTextArea.test.tsx, forms-flow-components/src/__test__/button.test.tsx, forms-flow-components/src/__test__/formInput.test.tsx, forms-flow-components/src/__test__/pills.test.tsx, forms-flow-components/src/__test__/tabs.test.tsx, forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_variables.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4202
https://jam.dev/c/d9c7f85b-6a40-4ecf-8e54-7edb072ae8fe
=> FWF-4202:[Feature]- updated dataTestid to dataTestId

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: https://aottech.atlassian.net/browse/FWF-4343
Internationalization for client form listing page.
=> FWF-4343:[Feature]- Internationalization for client form listing page

.github/workflows/forms-flow-component-ci.yml, forms-flow-admin/src/components/roles/roles.tsx, forms-flow-admin/src/constants/index.ts
JIRA: https://aottech.atlassian.net/browse/FWF-4276
=> FWF-4276 [feature] enabled edit for default role and optimized code

forms-flow-components/package-lock.json, forms-flow-components/package.json, forms-flow-components/src/__test__/ImportModal.test.tsx, forms-flow-components/src/__test__/NoDataFound.test.tsx, forms-flow-components/src/__test__/SortModal.test.tsx, forms-flow-components/src/components/CustomComponents/ImportModal.tsx
=> Test case implemented for sort and import modal

forms-flow-components/src/__test__/DropdownMultiSelect.test.tsx, forms-flow-components/src/components/CustomComponents/DropdownMultiselect.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4354
1.Added testcase for dropdown multiselect
=> feature/fwf-4354:added dropdown-multiselect testcase

forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4103
=> skipped # and +

forms-flow-service/package-lock.json, forms-flow-service/package.json
=> updated keycloak-js

forms-flow-components/src/__test__/historyModal.test.tsx, forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx, forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4233
=> FWF-4233: [Feature] Added unit tests for history modal

scripts/index.js
changes related to packaging images for RSBC
=> Aurelio changes related to packaging images for RSBC

forms-flow-components/src/components/CustomComponents/Button.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4333
=> FWF-4333 : [Feature] Added button variant with icon only

forms-flow-components/src/components/CustomComponents/Button.tsx
=> FWF-4389 : [BugFix] header ui issue fixed

forms-flow-components/src/components/CustomComponents/ImportModal.tsx, forms-flow-nav/src/root.component.js, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-nav/src/sidenav/Sidebar.scss, forms-flow-theme/scss/_aiAssistant.scss, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/fileUpload.scss, forms-flow-theme/scss/inputBox.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4349
Custom Theming updates
new style variables added
=> FWF-4349 [Patch] theming changes for patch 7.0.1

forms-flow-nav/src/constants/constants.js, forms-flow-nav/src/sidenav/Sidebar.jsx
=> Changes : user role from token and user name from user details 

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_table.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4344
Table CSS update for Client table
=> FWF-4344:[Feature] - Draft and submission table UI updates

forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4350
https://aottech.atlassian.net/browse/FWF-4388
formio tabs and hidden field style issue fixed
#SCREENSHOT
=> formio tabs and hidden field issue fixed

forms-flow-service/src/keycloak/KeycloakService.ts
JIRA: https://aottech.atlassian.net/browse/FWF-4415
=> FWF-4415 [bug] fixed auto logout issue in new user

forms-flow-admin/src/components/users/users.scss, forms-flow-nav/src/constants/constants.js, forms-flow-nav/src/root.component.js, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4402
changes : 
1.client header issue fix 
2.font family issue fix
3.danger color issue fix
=> custom theming updates for patch 7.0.1

forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4402
1.box shadow marked as none in form-check-inputs and form-control
=> css fix for patch 7.0.1

forms-flow-theme/Dockerfile
=> Update Dockerfile of theme

.github/workflows/forms-flow-microfrontend-cd.yml
Removed path filters from workflow
=> Removed path filters from workflow

forms-flow-nav/src/root.component.js, forms-flow-nav/src/sidenav/Sidebar.scss, forms-flow-service/src/helpers/styleService.ts, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4439
1.added util for css setting 
2.added  variable  --custom-logo-height
=> additional changes for custom theming

forms-flow-nav/src/root.component.js
JIRA: https://aottech.atlassian.net/browse/FWF-4439
1.update in useEffect which setting the header height
=> update in useEffect which setting the header height 

forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4346
1.Added max and min height for form container
=> bugfix/fwf-4346:Fixed height issue of form container

nginx.conf
JIRA: 
updated nginx to avoid cors
=> updated nginx to avoid cors

CODEOWNERS
=> Create CODEOWNERS for rsbc

CODEOWNERS
=> Create CODEOWNERS for formsflow team

forms-flow-components/src/components/SvgIcons/index.tsx
JIRA:  FWF-4344
Added Connect Icon
=> FWF-4344:[Feature]-Connect Icon Added

forms-flow-rsbcservice/src/endpoints/config.ts, forms-flow-rsbcservice/src/services/offlineSubmissions.ts
JIRA: 
Formio URL fix for the create API
https://aottech.atlassian.net/jira/software/projects/FOFR/boards/94/backlog?selectedIssue=FOFR-112
=> Formio URL fix for the create api

forms-flow-nav/src/sidenav/Sidebar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-4443
Fetching tenantKey from user details to ensure it is always available. Previously, tenantId could be undefined when tenant details were retrieved via an API call.
=> FWF-4443 [bugfix] fixed tenant id changed to undefined

forms-flow-components/src/__test__/dateFilter.test.tsx
=> [Bugfix] Formsflow component CD failure fix

forms-flow-rsbcservice/src/helpers/helperDbServices.ts, forms-flow-rsbcservice/src/services/offlineSubmissions.ts, forms-flow-rsbcservice/src/storage/dbInsertServices.ts, forms-flow-rsbcservice/src/storage/dbUpdateServices.ts, forms-flow-rsbcservice/src/storage/ffDb.ts
msg updated (#58)
JIRA: 
background sync toast msg update #92
=> background sync toast msg update #92

forms-flow-admin/src/components/users/users.scss, forms-flow-nav/src/root.component.js, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-nav/src/sidenav/Sidebar.scss, forms-flow-service/src/helpers/styleService.ts, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/_variables.scss, forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4441
https://aottech.atlassian.net/browse/FWF-4350
https://aottech.atlassian.net/browse/FWF-4451
1.All the custom theming-related changes from the release have been added to the develop branch.
2.Navbar UI issue with border radius fixed
3.Hidden fields taking up space in form.io fixed
=> FWF-4441-release custom theming changes to develop

forms-flow-nav/package-lock.json, forms-flow-nav/package.json, forms-flow-nav/src/sidenav/DateTimeNetworkWidget.jsx, forms-flow-nav/src/sidenav/Sidebar.jsx, forms-flow-nav/src/sidenav/Sidebar.scss
added date time and network status in sidebar (#62)
JIRA: 
https://github.com/divyav-aot/forms-flow-ai-micro-front-ends/pull/62
=> added date time and network status in sidebar (#62)

forms-flow-components/src/components/CustomComponents/Button.tsx, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4464
Style corrections for client screens
Added table button style variations
=> FWF-4464 [Bugfix] Stlye corrections for client screen and added table button variations

forms-flow-components/src/components/CustomComponents/ImportModal.tsx, forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_table.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4355
1. Button style changes
=> bugfix/fwf-4355:Fixed button style issues

.github/workflows/pr-review-agent.yml
=> Feature [added] pr review agent

forms-flow-theme/scss/_layout.scss
=> Show scrollbar

.github/workflows/forms-flow-theme.yml
=> env added for theme yml(#74)

VERSION
VERSION updated to v7.0.0-rsbc-v0.3.8 (#75)
=> VERSION updated to v7.0.0-rsbc-v0.3.8 (#75)

forms-flow-nav/src/sidenav/Sidebar.jsx
Navigating to home page in react way to avoid page reloading during offline
=> Navigating to home page in react way to avoid page reloading during offline

forms-flow-review/src/Routes/TaskDetails.tsx, forms-flow-theme/scss/_card.scss
JIRA: 
Issue Type: HOTFIX
___
Bug fix
___
- Detect custom header CSS variables usage  
- Dynamically set scroll container class  
- Define scrollable SCSS classes for header offsets  
- Add top margin to editor header
___
```mermaid
flowchart LR
A["StyleServices.getCSSVariable"] -- "fetch logo & title vars" --> B["hasMultitenancyHeader"]
B -- "true/false" --> C["scrollableOverview classname"]
C -- "apply to <div> wrapper" --> D["TaskDetails render"]
D -- "CSS height & overflow" --> E[".task-view-container-with(-custom)-header"]
```
<tr>
<td>
<details> …
=> FWF-4983:[HotFix] - Task Header hidign issue in task details page.

forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
JIRA: 
___
Bug fix
___
- Add null check for `inputFields` with optional chaining
- Ensure `.some` only runs when defined
- Prevent runtime errors on undefined `inputFields`
- Maintain `isActionDisabled` logic unchanged
___
```mermaid
flowchart LR
A["inputFields?"] --> B["hasAnyInputInFields"]
B --> C["isActionDisabled"]
D["dropdownSelection"] --> C
```
<tr>
<td>
<details>
<summary><strong>CollapsibleSearch.tsx</strong><dd><code>Null-check inputFields for safety</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> added null check for input fields

forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
JIRA: 
___
Bug fix
___
- Add optional chaining on prevFields.map call
- Add optional chaining on inputFields.map call
- Prevent errors when inputFields is null
___
<tr>
<td>
<details>
<summary><strong>CollapsibleSearch.tsx</strong><dd><code>Add optional chaining to inputFields maps</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
<ul><li>Added optional chaining to <code>prevFields.map</code> in handleClear<br> <li> …
=> added null check for input fields map

forms-flow-review/src/api/services/filterServices.ts, forms-flow-review/src/components/TaskForm.tsx, forms-flow-review/src/components/TaskList/TasklistTable.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4900
https://aottech.atlassian.net/browse/FWF-4963
https://aottech.atlassian.net/browse/FWF-4974
1.form component remounting issue fix and skeleton loader in task page
2.loader issue fixed
___
___
- Manage aborts and loader flags in service calls
- Fix form remount through key and read-only default
- Integrate Loading component for empty table state
- Clean up JSX formatting and code structure
___
```mermaid
flowchart LR
A["User triggers data fetch"] --> B["fetchServiceTaskList"]
B -- "set loader & abort prev calls" --> C["API Request"]
C -- "update tasks & count"] --> D["Redux Store"]
D --> E["TaskListTable renders data or Loading"]
F["TaskForm"] -- "toggle key via isReadOnly"] --> G["Form …
```
=> FWF-4900[Bugfix]form component remounting issue fix and skeleton loader in task page

forms-flow-review/src/components/TaskList/TaskList.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-5126
___
Bug fix
___
- Prevent resetting filters when unsaved filter present
- Add `isUnsavedFilter` to TaskList selector
- Early return and loader handling in initialDataLoading
- Depend on `isUnsavedFilter` in useEffect deps
___
<tr>
<td>
<details>
<summary><strong>TaskList.tsx</strong><dd><code>Handle unsaved filter in TaskList</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> bugfix/FWF-5126 [bugfix] retain unsaved filter

forms-flow-nav/src/root.component.js
JIRA: 
https://aottech.atlassian.net/browse/FWF-4449
___
Bug fix
___
- Add `logoError` state to track image errors
- Include `onError` handler on logo `<img>`
- Prevent rendering broken logo if errored
___
```mermaid
flowchart LR
A["Fetch customLogoPath"] -- "provided" --> B["Render logo `<img>`"]
B -- "error on load" --> C["setLogoError(true)"]
C -- "logoError true" --> D["Hide logo image"]
```
<tr>
<td>
<details>
<summary><strong>root.component.js</strong><dd><code>Add logo load error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> FWF-4449 [bugfix] updated error handle on image tag

forms-flow-submissions/src/Routes/SubmissionListing.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4557
___
Bug fix
___
- Rename `applicationStatus` field to `application_status`
- Update `pinnedOrder` array accordingly
___
<tr>
<td>
<details>
<summary><strong>SubmissionListing.tsx</strong><dd><code>Rename status key to snake_case</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
forms-flow-submissions/src/Routes/SubmissionListing.tsx
<ul><li>Changed …
=> FWF-4557: [Feature] variable key updated

forms-flow-review/src/index.tsx, forms-flow-submissions/src/components/View.tsx, forms-flow-submissions/src/index.tsx, forms-flow-theme/scss/_variables.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4988
#Screenshot 
___
Enhancement
___
- Add dynamic multi-tenancy header support
- Conditional container class based on CSS variables
- New scrollable overview classes for wizard
- Extend theme SCSS for custom header variants
___
```mermaid
flowchart LR
A["StyleServices.getCSSVariable"] --> B["hasMultitenancyHeader check"]
B --> C["Apply conditional container class"]
C --> D["Set dynamic scrollable overview class"]
D --> E["_variables.scss defines new styles"]
```
<tr>
<td>
<details> …
=> FWF-4988:[Bugfix] - Updated classes to fix header visibility issue MF

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx, forms-flow-theme/scss/_modal.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-5096
___
___
- Show dynamic role creation error message
- Change attribute filter buttons container class
- Add iconWithText prop to filter buttons
- Adjust modal left panel sizing
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>roles.tsx</strong><dd><code>Show dynamic toast error message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> FWF-5096 [bugfix] fixed style issue

forms-flow-review/src/api/services/filterServices.ts, forms-flow-review/src/components/Assigne/Assigne.tsx
=> [Bugfix] Test consoles and removed skeleton in task page for testing

forms-flow-review/src/api/services/filterServices.ts, forms-flow-review/src/components/TaskFilterModal/TaskFilterModal.tsx
=> [Bugfix] Removed empty array assigning condition to task list if an error occurs

forms-flow-review/src/Routes/TaskDetails.tsx
…are coming properly in task details
JIRA: 
=> [Bugfix] Removed test console to check the assignee comparison users are coming properly in task details

forms-flow-admin/src/components/roles/permissionTree.tsx, forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_table.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5094
- Text change to access manage 
-Pagination Dropdown 
-Anonymous form UI issues 
-Build form modal UI glitch
___
___
- Special-case admin permission label
- Remove loader icon from form inputs
- Add scrolling container to workflow editor
- Update form and table hover styling
___
<tr>
<td>
<details>
<summary><strong>permissionTree.tsx</strong><dd><code>Special-case admin permission label</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> FWF-5094:[Bugfix] - Designer Journey bugfixes

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-components/src/service/ExportAsPdf/downloadPdfButton.tsx, forms-flow-submissions/src/Routes/SubmissionListing.tsx, forms-flow-theme/scss/_theme.scss, forms-flow-theme/scss/bpmn.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5097
https://aottech.atlassian.net/browse/FWF-5132
1.Analyze submission ui issues fixed
2.Close icon issue in theming fixed
#screenshot 
___
___
- Switch icons to primary CSS color
- Add darkPrimary prop to Export PDF button
- Improve table header sorting and resizing
- Update scrollbar and BPMN container styles
___
<tr>
<td>
<details>
<summary><strong>index.tsx</strong><dd><code>Update icon classes to primary</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> FWF-5097:[bugfix] - analyze submission page ui fixes

forms-flow-components/src/components/CustomComponents/ButtonDropdown.tsx, forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx, forms-flow-theme/scss/collapsibleSidebar.scss
JIRA: 
1. fixed style issues 
2.
___
___
- Use string literal for `className` in ButtonDropdown
- Add dynamic `className` to `Dropdown.Item`
- Highlight selected form items in CollapsibleSearch
- Update sidebar height and scroll styling
___
<tr>
<td>
<details>
<summary><strong>ButtonDropdown.tsx</strong><dd><code>Refactor dropdown toggle and items classNames</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
forms-flow-components/src/components/CustomComponents/ButtonDropdown.tsx
<ul><li>Removed template …
=> fixed noted style issues in analyse submissions

forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-components/src/components/CustomComponents/Tabs.tsx, forms-flow-components/src/components/CustomComponents/VariableModal.tsx, forms-flow-submissions/src/Routes/SubmissionListing.tsx, forms-flow-theme/scss/_button.scss, forms-flow-theme/scss/_modal.scss
JIRA:  https://aottech.atlassian.net/browse/FWF-5136 
https://aottech.atlassian.net/browse/FWF-5139
https://aottech.atlassian.net/browse/FWF-5143
1. Allowed view in the disabled state of variable modal
2. buttondropdown hover and selected state style fix 
3. Fixed Delay in opening Form selection modal
___
___
- Replace CloseIcon with ClearIcon in inputs
- Add loading spinner in VariableModal form tab
- Support disabled-state styling in variable modal
- Prevent redundant fetch in SubmissionListing
___
```mermaid
flowchart LR
A["SubmissionListing"] -- "click manage fields" --> B["fetchFormData"]
B -- "set isFormFetched" --> C["VariableModal"]
C -- "isLoading?" -- Yes --> D["Loading spinner"]
C -- "isLoading?" -- No --> E["Form Tab Content"]
```
<details> …
=> feature/fwf-5136:Allowed view in disabled state of variable modal

forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx, forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-submissions/src/Routes/SubmissionListing.tsx, forms-flow-theme/scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5138
*  Search should reset if cleared the current search data
*  Fixed search data persisting issue when switching between filters
*  Added clear icon for form input in search
*  Removed button disabling for search and clear
___
___
- Add live search filtering to dropdown
- Add clear icon and reset input handlers
- Reset global filters on dropdown change
- Refactor sort handler in submission listing
___
```mermaid
flowchart LR
CS["CollapsibleSearch"]
CS -- "onSearch(query)" --> SQ["setSearchQuery"]
SQ -- "filter formData" --> DI["DropdownItems"]
FI["FormInput"] -- "onClearClick" --> CV["clear value"]
SL["SubmissionListing"]
SL -- "dropdown change" --> CF["clearSearchFieldValues"]
CF -- "reset filters" --> …
```
=> FWF-5138 : [BugFix] Resolved bugs of analyze submissions

forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
JIRA:  https://aottech.atlassian.net/browse/FWF-5150
DEPENDENCY PR:
https://github.com/AOT-Technologies/forms-flow-ai/pull/2910
1.  Updated queryparam 
2
___
___
Switch forms query to `allForms=true`
Fetch now targets all forms, not active
Aligns submissions listing with new API
Minor service update, no interface changes
___
```mermaid
flowchart LR
A["analyzeSubmissionServices.fetchAllForms"] -- updates query --> B["RequestService.httpGETRequest"]
B -- now calls --> C["API.FORM?allForms=true"]
A -. previously .-> D["API.FORM?activeForms=true"]
```
<tr> …
=> [modified]fwf-5150: updated query param for all form listing in submission

forms-flow-service/src/keycloak/KeycloakService.ts
* Fix delay happening during authentication
=> Fix/auth delay (#3)

forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: https://aottech.atlassian.net/browse/FWF-5173
#Screenshots: 
___
Enhancement, Documentation
___
- Add new unpublish modal heading key
- Replace "Confirm Unpublish" copy with explanation
- Update cancel CTA to keep published
- Provide translations across six locales
___
```mermaid
flowchart LR
EN["EN resource bundle"] -- add/replace strings --> Modal["Unpublish modal copy"]
BG["BG resource bundle"] -- translations --> Modal
DE["DE resource bundle"] -- translations --> Modal
ES["ES resource bundle"] -- translations --> Modal
FR["FR resource bundle"] -- translations --> Modal
PT["PT resource bundle"] -- translations --> Modal
ZH["ZH resource bundle"] -- translations --> Modal
``` …
=> FWF-5173":[Feature] - Updated the Publish-Unpublish Modal text.

forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx, forms-flow-review/src/components/TaskList/TasklistTable.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-5151
___
___
- Correct date filter payload formatting
- Format datetime to Camunda ISO in filters
- Render datetime with local date and time
- Render date fields as dd-mm-yyyy
___
```mermaid
flowchart LR
Filters["AttributeFilterModal: build filter values"] -- "day -> %MM/DD/YYYY%" --> Camunda["Camunda query"]
Filters -- "datetime -> %ISO8601%" --> Camunda
TaskVars["TasklistTable: resolve cell values"] -- "datetime -> local date & time" --> UI["Table cells"]
TaskVars -- "day -> dd-mm-yyyy" --> UI
```
<tr>
<td> …
=> FWF-5137 : [Feature] Fixed date & time issue in taskList table

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-service/src/constants/constants.ts, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/_table.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5103
https://aottech.atlassian.net/browse/FWF-5118
Style updates for ee
___
___
- Add color styling to `SortIcon` path
- Simplify env URL constants with safe defaults
- Bundle-specific modal and table style tweaks
- Improve modal footer layout flexibility
___
```mermaid
flowchart LR
Icons["SvgIcons: SortIcon stroke color"] -- visual tweak --> UI["UI consistency"]
Consts["Service constants: env URLs"] -- optional chaining, defaults --> Stability["Runtime stability"]
ModalSCSS["_modal.scss: bundle/footer/header tweaks"] -- layout updates --> BundleUI["Bundle-specific UX"]
TableSCSS["_table.scss: bundle table height"] -- scrolling control --> BundleUI
```
<details> <summary><h3> File …
=> FWF-5103/style changes for ee

forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx, forms-flow-service/src/resourceBundles/bg/resourceBundles.ts, forms-flow-service/src/resourceBundles/de/resourceBundles.ts, forms-flow-service/src/resourceBundles/en/resourceBundles.ts, forms-flow-service/src/resourceBundles/es/resourceBundles.ts, forms-flow-service/src/resourceBundles/fr/resourceBundles.ts, forms-flow-service/src/resourceBundles/pt/resourceBundles.ts, forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: 
https://aottech.atlassian.net/browse/FWF-4493
https://jam.dev/c/db8a6fa7-8191-4016-aaf5-6c2f58efc576
___
Bug fix, Enhancement, Documentation
___
- Show bundle note, hide manage fields
- Detect selected form type from data
- Add i18n strings for bundle note
- Minor UI accessibility/test-id updates
___
```mermaid
flowchart LR
collap["CollapsibleSearch.tsx"] -- "checks formType === 'bundle'" --> note["Render CustomInfo note"]
collap -- "else" --> manage["Show 'Manage fields' button"]
i18n["Resource bundles (EN/DE/FR/ES/PT/ZH/BG)"] -- "add translation keys" --> note
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug …
=> bugfix/FWF-4493 [bugfix] note rendering for bundle forms

forms-flow-submissions/src/Routes/SubmissionListing.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-5151
___
___
- Fix datetime columns local timezone rendering
- Use active field set for value formatting
- Preserve created date localized formatting
- Minor refactor for readability
___
```mermaid
flowchart LR
A["currentFields from selected filter"] -- "find matchingField" --> B["detect type === datetime"]
B -- "format" --> C["HelperServices.getLocalDateAndTime"]
A -- "created field" --> D["format created date"]
D -- "render" --> E["customTdValue in row"]
C -- "render" --> E
```
<tr>
<td>
<details> …
=> FWF-5151 : [BugFix] Analyze-submission date display fix

forms-flow-submissions/src/Routes/SubmissionListing.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-5241
___
___
- Reset sort orders before applying new sort
- Fix analyze-submission column sort state
- Centralize reset via HelperServices utility
___
```mermaid
flowchart LR
UI["Analyze Submission Listing"] -- "click column header" --> handleSort["handleSort(key)"]
handleSort -- "reset via HelperServices.getResetSortOrders" --> resetState["reset sortParams"]
handleSort -- "set new sort order + activeKey" --> dispatchSort["dispatch setAnalyzeSubmissionSort"]
SortModal["Sort Modal Apply"] -- "apply selection" --> handleSortApply["handleSortApply(option, order)"]
handleSortApply -- "reset + set activeKey/order" --> dispatchSort
``` …
=> FWF-5241 : [BugFix] Column sort issue fixed in analyze-submission listing

forms-flow-admin/src/components/roles/roles.tsx, forms-flow-review/src/api/services/filterServices.ts
JIRA: https://aottech.atlassian.net/browse/FWF-5224
https://aottech.atlassian.net/browse/FWF-5170
1.fixed custom header issue in roles page when edit modal is opened
2.fixed loading issue in task table when switching pages and on after refreshing
___
Bug fix
___
- Prevent focus reset in edit modal
- Ensure abort flag set after tasks fetch
___
```mermaid
flowchart LR
roles["Roles edit modal"] -- "add restoreFocus=false" --> focus["Prevent focus reset"]
filter["fetchServiceTaskList"] -- "set abortFlag when data present" --> stability["Avoid duplicate/abort issues"]
```
<tr>
<td> …
=> FWF-5170[bugfix]custom header issue in roles page

forms-flow-components/src/components/CustomComponents/FormComponent.tsx, forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx, forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx, forms-flow-review/src/components/TaskList/TaskList.tsx, forms-flow-review/src/components/TaskList/TasklistTable.tsx, forms-flow-review/src/components/constants/taskConstants.ts, forms-flow-review/src/helper/tableHelper.ts, forms-flow-review/src/helper/taskHelper.ts, forms-flow-submissions/src/constants/variables.ts
JIRA: https://aottech.atlassian.net/browse/FWF-4841
1. Added more sort options in table header
2. Sorting is available for some of the form components. 
3. Removed fileupload , signature , password components from variable selection modal (generic to all variable selection modals).
4.  In analyse - submission , removed the ' Current User' from SYSTEM tab.
5. Enabled radio button in task filter and tested with attribute filter 
6. Displayed checkbox data in task table as true or false 
___
___
- Enable sorting for dynamic form variables
- Add type-aware sort payload to API
- Show boolean values as True/False
- Remove non-sortable components from selection
___
```mermaid
flowchart LR
UI["Task List UI"] -- "choose sort option" --> SortModal["Sort …
```
=> feature/fwf-4841:Added sorting for columns in review table

forms-flow-admin/package-lock.json, forms-flow-admin/package.json, forms-flow-components/package-lock.json, forms-flow-components/package.json, forms-flow-components/src/components/CustomComponents/Pills.tsx, forms-flow-nav/package-lock.json, forms-flow-nav/package.json, forms-flow-review/package-lock.json, forms-flow-review/package.json, forms-flow-service/package-lock.json, forms-flow-submissions/package-lock.json, forms-flow-submissions/package.json, forms-flow-theme/scss/_button.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-5198
___
___
- Upgrade react-bootstrap to 2.10.6
- Migrate Badge prop from variant to bg
- Adjust dropdown menu layout CSS
- Align peerDependencies with new version
___
```mermaid
flowchart LR
deps["Bump react-bootstrap to 2.10.6"]
pills["Update Badge prop: variant -> bg"]
styles["Tweak dropdown menu CSS"]
packages["Update dependencies/peers across packages"]
deps -- "requires API changes" --> pills
deps -- "consistency across apps" --> packages
deps -- "style behavior change" --> styles
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>2 …
=> updated react bootstrap version to 2.10.6

forms-flow-components/src/components/CustomComponents/Pills.tsx, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_modal.scss, forms-flow-theme/scss/external/formio.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-5312
___
___
- Update pills to Bootstrap rounded badge
- Add tabs styling for new structure
- Ensure nav-link buttons are transparent
- Align Form.io badge class names
___
```mermaid
flowchart LR
Pills["Pills.tsx props formatting"] -- "minor prop spacing" --> TSX["Type cleanup"]
FormsSCSS["_forms.scss"] -- "tabs/nav support for new structure" --> Tabs["Anchor & button .nav-link styles"]
FormsSCSS -- "badge class rename" --> PillsCSS[".badge.rounded-pill styles"]
ModalSCSS["_modal.scss"] -- "use .badge.rounded-pill" --> ModalPills["Modal pill theming"]
FormioSCSS["formio.scss"] -- "update badge selectors" --> FormioBadges[".badge.bg-* colors"]
```
<details> <summary><h3> File …
=> FWF-5312 [upgrade] ui fix for pills and tabs

forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx, forms-flow-submissions/src/Routes/SubmissionListing.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-5147
___
___
- Add placeholder support to search inputs
- Map date/time types to example placeholders
- Pass placeholders into CollapsibleSearch FormInput
___
```mermaid
flowchart LR
A["SubmissionListing: derive placeholders by type"] -- "set field.placeholder" --> B["CollapsibleSearch: FormInput receives placeholder"]
B -- "improves UX for date/time search" --> C["Search panel"]
```
<tr>
<td>
<details>
<summary><strong>CollapsibleSearch.tsx</strong><dd><code>Support and pass placeholder to …
=> FWF-5148 : [Modified] Added placeholder for date and time searches in collapsible search

forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/_modal.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5311
expression builder UI issues
___
___
- Adjust required icon styling globally
- Refine form group icon rules
- Add specs text style in tabs
- Improve expression list variable layout
___
```mermaid
flowchart LR
A["_forms.scss"] -- "Global required icon style" --> C["Consistent form indicators"]
B["_modal.scss"] -- "Specs text + variable layout" --> D["Clearer expression builder UI"]
C -- "Improved consistency" --> E["Enhanced UX"]
D -- "Visual clarity" --> E
```
<tr>
<td>
<details> …
=> FWF-5311[bugfix]expression builder UI issues

forms-flow-components/src/components/CustomComponents/InputDropdown.tsx, forms-flow-theme/scss/_button.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-5344
___
Enhancement
___
- Add `useAbsolutePosition` prop for dropdown
- Toggle absolute/relative dropdown positioning
- Introduce `template-override` CSS class hook
- Clean up commented dropdown rendering code
___
```mermaid
flowchart LR
InputDropdown["InputDropdown component"] -- "adds prop" --> useAbsolutePosition["useAbsolutePosition:boolean"]
useAbsolutePosition -- "controls class" --> selectOptions["div.select-options"]
selectOptions -- "adds when true" --> templateOverride["class 'template-override'"]
SCSS["_button.scss styles"] -- "default position: relative" --> selectOptions
templateOverride -- "forces absolute position" --> SCSS
``` …
=> FWF-5344 [Upgrade] updated styling and ovverride style for template

.github/workflows/pr-notification.yml, VERSION, forms-flow-admin/package-lock.json, forms-flow-admin/package.json, forms-flow-components/package-lock.json, forms-flow-components/package.json, forms-flow-integration/package-lock.json, forms-flow-integration/package.json, forms-flow-nav/package-lock.json, forms-flow-nav/package.json, forms-flow-review/package-lock.json, forms-flow-review/package.json, forms-flow-service/package-lock.json, forms-flow-service/package.json, forms-flow-submissions/package-lock.json, forms-flow-submissions/package.json, forms-flow-theme/package-lock.json, forms-flow-theme/package.json
--> Updated the version in package, package-lock and version files from 7.2.0-alpha to 8.0.0-alpha
--> Updated Google notification workflow with adding v8-develop branch.
___
Enhancement, Other
___
- Bump versions to v8.0.0-alpha
- Add v8-develop to PR notifications
- Update root VERSION to 8.0.0-alpha
___
```mermaid
flowchart LR
A["Workflow pr-notification.yml"] -- "add branch" --> B["v8-develop monitored"]
C["Root VERSION"] -- "set" --> D["v8.0.0-alpha"]
E["Package versions (8 packages)"] -- "bump" --> F["v8.0.0-alpha"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>2 files</summary><table>
<tr> …
=> Version Update and Google Notification for v8-develop.

forms-flow-components/src/components/CustomComponents/ImportModal.tsx, forms-flow-components/src/components/CustomComponents/ProgressBar.tsx, forms-flow-theme/scss/fileUpload.scss, forms-flow-theme/scss/v8-scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5346
1.updated progress bar
#Screenshots   
___
Enhancement
___
- Replace bootstrap ProgressBar with custom component
- Animate progress capped on error state
- Add theming via CSS variable for bar color
- Update SCSS to use new variables
___
```mermaid
flowchart LR
ImportModal["ImportModal.tsx"]
CustomPB["CustomComponents/ProgressBar.tsx"]
ThemeSCSS["v8-scss/_theme.scss"]
UploadSCSS["scss/fileUpload.scss"]
ImportModal -- uses --> CustomPB
CustomPB -- sets CSS var --> ThemeSCSS
ThemeSCSS -- exposes var --> UploadSCSS
UploadSCSS -- styles --> ProgressBar
```
<table><thead><tr><th></th><th align="left">Relevant …
=> FWF-5346[feature] - progress bar for v8

forms-flow-components/src/components/CustomComponents/CustomButton.tsx, forms-flow-components/src/components/index.ts, forms-flow-theme/scss/index.scss, forms-flow-theme/scss/v8-scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5211
https://aottech.atlassian.net/browse/FWF-5210
1. Added button with loading and icon-only button 
2. 
1. icon-only button 
selected and loading 
loading 
Disabled 
2. Button 
Disabled button 
Active button with icon
selected button  with icon
loading button with icon 
active button 
___
Enhancement
___
- Add `V8CustomButton` React component
- Support loading, disabled, selected states
- Add icon-only and full-width options
- Introduce SCSS styles and exports
___
```mermaid
flowchart LR
A["V8CustomButton.tsx"] -- "export added" --> B["components index.ts"]
A["V8CustomButton.tsx"] -- "uses classes" --> C["_button.scss"]
D["theme index.scss"] -- "imports" --> C["_button.scss"]
```
<details> <summary><h3> File …
=> feature/fwf-5210-5211: Added button and icon-only button

forms-flow-components/src/components/CustomComponents/Search.tsx, forms-flow-theme/scss/index.scss, forms-flow-theme/scss/v8-scss/_search.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5214
1. Added search input 
Inactive 
active 
search typed 
___
Enhancement
___
- Simplified search input component
- Added dedicated search SCSS styles
- Integrated new styles into theme index
___
```mermaid
flowchart LR
SearchTSX["Search.tsx: Simplified component"] -- "uses" --> useTranslation["i18next useTranslation"]
SearchTSX -- "styled by" --> SearchSCSS["v8-scss/_search.scss"]
ThemeIndex["scss/index.scss"] -- "imports" --> SearchSCSS
```
<tr>
<td>
<details>
<summary><strong>Search.tsx</strong><dd><code>Simplify Search …
=> feature/fwf-5214:Added search input component

forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx, forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-5368
___
Bug fix
___
- Correct checkbox and currency type checks
- Use unique keys for checkbox dropdown
- Fix selected value handling for booleans
- Align payload mapping to original keys
___
```mermaid
flowchart LR
TV["Task variables (original keys)"] -- "resolve unique key" --> UK["Unique field key"]
UK -- "build dropdown + ids" --> UI["Checkbox InputDropdown"]
UI -- "selected value (true/false)" --> Handler["handleSelectChange(uniqueKey, val)"]
TV -- "type lookup (originalKey)" --> Types["types[originalKey]"]
Types -- "checkbox/currency -> eq" --> Operator["operator selection"]
Types -- "currency/number -> Number(value)" --> Value["value normalization"]
``` …
=> FWF-5368 [bugfix] updated payload structure for checkbox

forms-flow-components/src/components/CustomComponents/Radio.tsx, forms-flow-components/src/components/Stories/CustomRadioButton.stories.tsx, forms-flow-theme/scss/_forms.scss, forms-flow-theme/scss/index.scss, forms-flow-theme/scss/v8-scss/_radio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5208
Added Radio button component
___
Enhancement, Tests, Documentation
___
- Rebuilt accessible radio group component
- Added Storybook stories and controls
- Implemented new V8 radio SCSS styles
- Removed legacy radio styles
___
```mermaid
flowchart LR
RadioTSX["CustomRadioButton (Radio.tsx)"]
Stories["Storybook stories (CustomRadioButton.stories.tsx)"]
OldStyles["Remove old radio styles (_forms.scss)"]
NewStyles["Add V8 radio styles (_radio.scss)"]
IndexScss["Include radio styles (index.scss)"]
RadioTSX -- "exports component" --> Stories
NewStyles -- "imported into" --> IndexScss
OldStyles -- "replaced by" --> NewStyles
```
<table><thead><tr><th></th><th …
=> Feature/fwf 5207 UI checkbox

forms-flow-theme/scss/bpmn.scss, forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5349
___
___
- Add reusable border utility classes
- Tweak BPMN editor container sizing
- Align Formio breadcrumb badge colors
- Style nav tabs within Formio builder
___
```mermaid
flowchart LR
SCSS["Theme SCSS updates"] -- "add utilities" --> Border["Border classes (.border,.border-1,.border-dark)"]
SCSS -- "refine layout" --> BPMN["BPMN editor container sizing"]
SCSS -- "consistency" --> Badges["Formio breadcrumb badge colors"]
SCSS -- "new rule" --> Tabs["Formio nav tabs styling"]
```
<tr>
<td>
<details> …
=> FWF-5349 : [BugFix] Updated and overrided styles for ui fixes

forms-flow-components/src/components/CustomComponents/CustomCheckbox.tsx, forms-flow-components/src/components/Stories/CustomCheckbox.stories.tsx, forms-flow-theme/scss/index.scss, forms-flow-theme/scss/v8-scss/_checkbox.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5207
Added checkbox component
___
Enhancement, Documentation
___
- Add accessible CustomCheckbox component
- Provide Storybook stories and controls
- Introduce themed checkbox SCSS styles
- Integrate checkbox styles into theme index
___
```mermaid
flowchart LR
UI["CustomCheckbox.tsx"] -- "renders + a11y + i18n" --> Storybook["CustomCheckbox.stories.tsx"]
UI -- "uses classes" --> Styles["_checkbox.scss"]
Styles -- "imported in" --> ThemeIndex["theme index.scss"]
```
<tr>
<td>
<details> …
=> FWF-5207 : Added checkbox

forms-flow-components/src/components/CustomComponents/FormInput.tsx, forms-flow-theme/scss/_button.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5336
___
___
- Add no-spinner class for number inputs
- Apply class conditionally based on input type
- Define CSS to hide number spinners
___
```mermaid
flowchart LR
TS["FormInput.tsx adds conditional 'no-spinner' class"] -- "when type === 'number'" --> DOM["Input element without spinners"]
CSS["_button.scss defines .no-spinner rules"] -- "hide webkit spin buttons" --> UI["Cleaner number input UI"]
```
<tr>
<td>
<details>
<summary><strong>FormInput.tsx</strong><dd><code>Conditionally add no-spinner class to …
=> FWF-5349 : [Modified] Removed increment, decrement icons for number input

forms-flow-review/src/Routes/TaskDetails.tsx, forms-flow-review/src/index.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-4959
___
Bug fix
___
- Fix tenant key retrieval fallback
- Align localStorage key names
- Prevent missing tenant data on load
___
```mermaid
flowchart LR
A["Redux tenant key"] -- "missing?" --> B["Fallback to localStorage 'tenantKey'"]
C["Load tenant data"] -- "from localStorage" --> D["Use 'tenantData' key"]
```
<tr>
<td>
<details>
<summary><strong>TaskDetails.tsx</strong><dd><code>Add tenantKey fallback from localStorage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> FWF-4959 [bugfix] redirect url fix initial tenantdata not setting

forms-flow-theme/scss/_card.scss, forms-flow-theme/scss/bpmn.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5409
___
___
- Fix BPMN editor overflow clipping
- Allow loading overlay to escape container
- Remove hidden overflow from editor
___
```mermaid
flowchart LR
A["BPMN editor styles"] -- "remove overflow hidden" --> B["Visible content & resizes"]
C["Workflow edit container"] -- "override overlay overflow" --> D["Loading overlay visible"]
```
<tr>
<td>
<details>
<summary><strong>_card.scss</strong><dd><code>Make loading overlay visible within workflow editor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
=> FWF-5409: [BugFix] bpmn modeler ui issue fix

forms-flow-components/src/components/SvgIcons/index.tsx, forms-flow-theme/scss/v8-scss/_formCreateLayout.scss, forms-flow-theme/scss/v8-scss/_theme.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5273
1. Added styles and icon for the formedit page
___
Enhancement
___
- Add new FormStatusIcon component
- Introduce FormEdit header styles
- Adjust grid header sections in theme
- Add FormEdit body layout rules
___
```mermaid
flowchart LR
Icons["SvgIcons: add FormStatusIcon"] -- used by --> Header["FormEdit header UI"]
ThemeHeader["Theme: header sections tweaks"] -- supports --> Layout["FormEdit layout"]
BodyStyles["Theme: body .formedit-layout rules"] -- define --> Layout
SCSS["FormEdit SCSS: title/status styles"] -- style --> Header
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td>< …
=> feature/fwf-5273:Added styles for formedit page

forms-flow-nav/src/sidenav/Sidebar.scss, forms-flow-theme/scss/index.scss, forms-flow-theme/scss/v8-scss/_formCreateLayout.scss, forms-flow-theme/scss/v8-scss/_formEditSettings.scss, forms-flow-theme/scss/v8-scss/_mixins.scss, forms-flow-theme/scss/v8-scss/_theme.scss
JIRA:  https://aottech.atlassian.net/browse/FWF-5338
- Added Edit settings page layout, 
- -Updated Nave bar theme glitches and animation 
- -the settings page layout mixins can be used for edit action as well.
#Screenshotes 
https://jam.dev/c/e4bf4581-e809-43a6-b412-b4dd7f7581e1
___
Enhancement
___
- Implement edit settings layout mixins
- Refactor nav background variable usage
- Add hover/collapse sidebar transitions
- Import new edit settings styles
___
```mermaid
flowchart LR
Mixins["New layout mixins (_mixins.scss)"] -- "used by" --> EditSCSS[".form-edit-setiings styles (_formEditSettings.scss)"]
ThemeIndex["Theme index imports (index.scss)"] -- "imports" --> EditSCSS
Sidebar["Sidebar styles (Sidebar.scss)"] -- "use var" --> ThemeVars["Theme vars …
```
=> FWF-5338:[V8Feature] - Edit settings page layout
