- forms-flow-admin/src/components/users/users.tsx
https://aottech.atlassian.net/browse/FWF-2138
translated tooltip "No data Found" in users tab on admin in microfrontend
> internationalization update on microfrontend

- forms-flow-theme/src/overrideClasses/bootstrapOverride.scss
Issue : https://aottech.atlassian.net/browse/FWF-2770
Changes : Bundle table border removed 
Screenshot :
> Bundle table changes

- forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
- forms-flow-service/src/resourceBundles/de/resourceBundles.ts
- forms-flow-service/src/resourceBundles/en/resourceBundles.ts
- forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
- forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
- forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
https://aottech.atlassian.net/browse/FWF-2891
> Internationalization updates for DMN label changes

- forms-flow-theme/src/overrideClasses/bootstrapOverride.scss
> btn link text decoration fixed

- forms-flow-admin/src/components/dashboard/dashboard.tsx
The admin dashboard where showing an unexpected row due to a comparison issue issue in the code. 
https://aottech.atlassian.net/browse/FWF-3063
changed:
> Removed un-necessary conversion  to number of resources id

- forms-flow-admin/src/components/dashboard/dashboard.tsx
By converting item.id to a string before checking its inclusion in the authIds array, it mitigates any potential issues arising from comparing different types (string vs. integer). This approach ensures consistent behavior and prevents unexpected outcomes in the comparison.
https://aottech.atlassian.net/browse/FWF-3063
> Resource Id convertion to string

- forms-flow-nav/src/Navbar.jsx
In this pull request, the following changes have been made:
The `useEffect` code responsible for setting the application logo from tenant details has been removed. This change is based on the presence of an existing `useEffect` for this purpose.
Integrated code related to the favicon within this pull request.
Addressed a scenario where, in the absence of multitenancy, changing the `APPLICATION_NAME` from 'formsflow.ai' to another value resulted in the navbar displaying the new value while the browser title retained 'formsflow.ai'. This issue has been resolved to ensure consistency in the browser title.
These changes aim to improve code organization and address a specific scenario related to non-multitenant deployments, ensuring a more coherent and functional application.
> fixed navbar favicon and app name issue

- forms-flow-theme/scss/_aiAssistant.scss
- forms-flow-theme/scss/_layout.scss
- forms-flow-theme/scss/_variables.scss
Updated max-width to none for large monitors as it was showing lot of whitespace
Before : 
After :
> [Hotfix] : Styling fix for large monitors

- forms-flow-theme/scss/_modal.scss
JIRA: 
Height commented for common modal dialog as it is breaking settings modal layout
Before : 
After :
> FWF-3739 [Bugfix] Height commented for common modal dialog as it is breaking settings modal layout

- forms-flow-components/src/components/CustomComponents/BuildModal.tsx
- forms-flow-components/src/components/CustomComponents/Pills.tsx
- forms-flow-theme/scss/_forms.scss
- forms-flow-theme/scss/_modal.scss
JIRA: 
1. Updates to reusable pill component
2. style fix on buildmodal
> Updated reusable pill component

- .github/workflows/pr-notification.yml
- forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
> Fixed revert Button disabled

- forms-flow-components/src/components/CustomComponents/FormInput.tsx
- forms-flow-components/src/components/CustomComponents/ReusableProcessTableRow.tsx
- forms-flow-theme/scss/_modal.scss
- forms-flow-theme/scss/_table.scss
- forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-3661
1.Style added for Task variable modal its formio component
> fwf-3661:Added styles for task variable modal

- forms-flow-components/src/components/CustomComponents/ImportModal.tsx
JIRA: 
#Screenshot 
Display the new version being created while import in Edit page of DMN and BPMN
> FWF-3971:[Feature] - Subflow and Decesion Table Import version display

- forms-flow-components/src/components/CustomComponents/FormInput.tsx
- forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
- forms-flow-components/src/components/CustomComponents/TableFooter.tsx
- forms-flow-theme/scss/_forms.scss
- forms-flow-theme/scss/_table.scss
JIRA: 
1.Updated inputdropdown with onBlur 
#screenshots
> Updates to Custom inputdropdown component

- forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4064
The conform modal sometimes need to hide the secondary button so the button will be displayed now only if there is secondary button text in the props
> FWF-4064:[Feature]-Conform modal secondary button hide.

- forms-flow-components/src/components/CustomComponents/ImportModal.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-3971
The import button will be disabled if no versions are selected and chose both form and wrokflow as Skip, do not import.
> FWF-3971:[Feature]-Disable import modal's primary button.

- forms-flow-service/src/formsflow-services.ts
- forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
- forms-flow-service/src/resourceBundles/de/resourceBundles.ts
- forms-flow-service/src/resourceBundles/en/resourceBundles.ts
- forms-flow-service/src/resourceBundles/es/resourceBundles.ts
- forms-flow-service/src/resourceBundles/formioResourceBundle.ts
- forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
- forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
- forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
JIRA: https://aottech.atlassian.net/browse/FWF-3782
> Added some keys for translations for formio

- forms-flow-components/src/components/CustomComponents/DragandDropSort.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-4973
___
Bug fix
___
- Use `id` instead of `itemId` for unique keys
- Update JSX `key` and `input` IDs using `id`
- Remove deprecated `itemId` property
- Clean up `draggable` attribute formatting
___
<tr>
<td>
<details>
<summary><strong>DragandDropSort.tsx</strong><dd><code>Use id for list item keys and IDs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> FWF-4973: [BugFix] hide filter with same name issue fixed

- forms-flow-components/src/components/CustomComponents/FormComponent.tsx
- forms-flow-submissions/src/index.scss
- forms-flow-theme/scss/external/formio.scss
JIRA: https://aottech.atlassian.net/browse/FWF-5139
1. Prevented selection of survey component in variable modal 
2. fixed wizard form tab style issue  
___
Bug fix
___
- Prevent survey type selection in variable modal
- Add survey CSS class to ignore list
- Refactor pagination .page-item styles
___
```mermaid
flowchart LR
FC["FormComponent.tsx"]
TF["formio.scss"]
IN["index.scss"]
MOD["Variable Selection Modal"]
PAG["Pagination UI"]
FC -- "ignore survey type" --> MOD
TF -- "add .formio-component-survey class" --> MOD
IN -- "update page-link colors" --> PAG
```
<tr>
<td>
<details> …
> bugfix/fwf-5139:Fixed styles issues in variables selection modal

- forms-flow-submissions/src/Routes/SubmissionListing.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-5138
* Fixed : 
* Selected form getting resetting to default on redirecting back to submissions from View details page
* Collapse side bar is not active even though a filter is selected
___
Bug fix
___
- Persist default submission filter on selection
- Dispatch `setDefaultSubmissionFilter` and backend update
- Show active filter state when dropdown selected
- Update fields based on filter variables
___
<tr>
<td>
<details>
<summary><strong>SubmissionListing.tsx</strong><dd><code>Persist default filter and active status</code>&nbsp; &nbsp; …
> FWF-5138 : [BugFix] filter persist issue fixe, active filter fix

- forms-flow-submissions/src/Routes/SubmissionListing.tsx
JIRA: https://aottech.atlassian.net/browse/FWF-5138
* Fixed search not found while in another page issue
___
Bug fix
___
- Reset pagination on dropdown change
- Reset pagination on field search
- Dispatch page index reset action
___
<tr>
<td>
<details>
<summary><strong>SubmissionListing.tsx</strong><dd><code>Reset analyze page index on filters</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
forms-flow-submissions/src/Routes/SubmissionListing.tsx …
> FWF-5138 : [BugFix] Fixed search issue with another page

- forms-flow-theme/scss/_forms.scss
JIRA: https://aottech.atlassian.net/browse/FWF-4988
Fixed Header visibility issue in anonymous form
#Screenshot
___
___
- Separate heights for wizard vs normal form containers
- Increase wizard container height by 1rem
- Remove gap in `.userform-wrapper`
- Minor SCSS cleanup and refactoring
___
```mermaid
flowchart LR
A[".user-form-container"] --> B["height: calc(100vh - 7.5625rem - var(--client-nav))"]
C[".user-form-container-with-wizard"] --> D["height: calc(100vh - 8.5625rem - var(--client-nav))"]
```
<tr>
<td>
<details> …
> FWF-4988:[Feature] - Custom header adjustment for vizard forms

- forms-flow-theme/scss/fileUpload.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-5333
___
Enhancement
___
- Truncate long upload file names
- Prevent overflow in file name container
___
```mermaid
flowchart LR
SCSS["fileUpload.scss styles"] -- "add overflow handling" --> UploadName[".upload-file-name"]
UploadName -- "ellipsis + nowrap" --> TruncatedDisplay["Truncated file name display"]
```
<tr>
<td>
<details>
<summary><strong>fileUpload.scss</strong><dd><code>Handle long file names with ellipsis</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> FWF-5333 [update] style fix for form import

- forms-flow-components/src/components/CustomComponents/FormComponent.tsx
JIRA: 
https://aottech.atlassian.net/browse/FWF-5366
https://aottech.atlassian.net/browse/FWF-5330
___
___
- Use ref for form container
- Fix outside-click handling cleanup
- Improve selection logic dependencies
- Minor formatting and comments cleanup
___
```mermaid
flowchart LR
FormComponent["FormComponent.tsx"]
RefAdded["Add formHilighterRef"]
ClickLogic["Update click/selection logic"]
OutsideClick["Robust outside-click handling"]
RenderDiv["Ref on form container div"]
FormComponent -- "introduce useRef" --> RefAdded
RefAdded -- "used in effect" --> OutsideClick
FormComponent -- "adjust dependencies" --> ClickLogic
ClickLogic -- "controls selection & highlighting" --> OutsideClick
RefAdded -- "assigned to container" --> RenderDiv
``` …
> FWF-5366 [bugfix] updated logic of form variable selection
